routes/web.php
<?php

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['auth']], function () {

	Route::resource('staff', 'StaffController', ['except' => ['show']]);

	Route::get('/staff/show/{id}', 'StaffController@show');

	Route::post('/staff/file/handleUpload', 'StaffController@handleUpload');

    Route::resource('attendance', 'AttendanceController');

    Route::resource('salary', 'SalaryController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\AttendanceRequest;

use App\Model\Staff;

use App\Model\Attendance;



class AttendanceController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $attendance = Attendance::all();
        return view('app.attendance.attendance', compact('attendance', 'staff'));
    }

    public function create()
    {
        $staff = Staff::all();
        $attendance = Attendance::all();
        return view('app.attendance.create', compact('attendance', 'staff'));
    }

    public function store(AttendanceRequest $request)
    {
        $data = $request->all();

        if ($data['office_time'] == "arrival_time") {
            $data['arrival_time'] = date("Y-m-d h:i:s");
            $data['departure_time'] = date("Y-m-d h:i:s");
            $data['remarks'] = "Present";


        }

        if ($data['office_time'] == "departure_time") {
            $data['departure_time'] = date("Y-m-d h:i:s");

        }

        $attendance = new Attendance;
        $attendance->create($data);
        return redirect('attendance');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Model\Staff;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('app.pages.home');
    }

}

app/Http/Controllers/SalaryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Model\Staff;

class SalaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staff = Staff::all();
        return view('app.salary.index', compact('staff'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $staff = Staff::all();
        $staff = Staff::where('id',$id)->firstOrFail();
        return view('app/salary/edit', compact('staff'));    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StaffRequest;
use Session;
use App\Model\staff;
use \Storage;

class StaffController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $staff = Staff::all();
        $search = \Request::get('search');
        $staff = staff::where('first_name', 'like', '%' . $search . '%')
            ->orderBy('first_name')
            ->paginate(4);
        return view('app.staff.index', compact('staff'));
    }

 
    public function create()
    {
        return view('app/staff/create');
    }

    public function store(StaffRequest $request)
    {
        $data= $request->all();
        $staff = new Staff;
        $staff->create($data);
        return redirect('staff')->with('flash_message', 'Staff Information successfully added!');
    }

    public function show($id)
    {
        $staff = Staff::where('id',$id)->firstOrFail();
        return view('app/staff/show', compact('staff'));
    }

    public function edit($id)
    {
        $staff = Staff::where('id',$id)->firstOrFail();
        return view('app/staff/edit', compact('staff'));
    }


    public function update(Request $request, $id)
    {
         $staff = Staff::findOrFail($id);

            $this->validate($request, [
        'first_name' => 'required',
        'mobile' => 'required'
        ]);

        $data = $request->all();

        $staff->fill($data)->save();

        Session::flash('flash_message', 'Information Update successfully');

        return redirect()->back();
    }

    public function destroy($id)
    {
        $staff = Staff::where('id',$id)->firstOrFail();
        $staff->delete();
        Session::flash('delete_message', 'Successfully deleted!');
        return redirect()->back();     
    }

    public function handleUpload(Request $request){


             if($request->hasFile('file')){
             $file = $request->file('file');
             // $allowedFileTypes = config('app.allowedFileTypes');
             // $maxFileSize = config('app.maxFileSize');
        //     $rules = [
        //         'file' => 'required|mimes:'.$allowedFileTypes.'|max:'.$maxFileSize
        //     ];
        //     $this->validate($request, $rules);
             $fileName = $file->getClientOriginalName();
             $destinationPath = config('app.fileDestinationPath').'/'.$fileName;
             $uploaded = Storage::put($destinationPath, file_get_contents($file->getRealPath()));

             if($uploaded){
        //         UploadedFile::create([
        //             'filename' => $fileName
        //         ]);
             }
         }

         return redirect()->to('/staff/create');
    }



}

resources/views/app/attendance/attendance.blade.php
    @extends('app.layouts.default')
    @section('content')
        <div class="container">
            <h1>Attendance</h1>
            {{ link_to_route('attendance.create', 'Staff Attendance', null,['class'=>'btn btn-primary']) }}

            <hr>

            <section align="right">
                <h3>Staff Attendance Sheet</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th class="text-center">Card No.</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Post</th>
                        <th class="text-center">Arrival time</th>
                        <th class="text-center">Departure time</th>
                        <th class="text-center">Remarks</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($attendance as $a)
                        <tr>
                            <td>{{ $a->staff->id }}</td>
                            <td>{{ $a->staff->first_name." ".$a->staff->last_name }}</td>
                            <td>{{ $a->staff->position }}</td>
                            <td>{{ $a->arrival_time }}</td>
                            <td>{{ $a->departure_time }}</td>
                            <td>{{ $a->remarks }} </td>
                        </tr>
                @endforeach
                    </tbody>
            </section>


        </div>
    @stop

resources/views/app/attendance/create.blade.php
@extends('app.layouts.create')
@section('content')

    <div class="container">
        <h1>Staff Attendance</h1>
        {{ link_to_route('attendance.index', 'Attendance sheet', null,['class'=>'btn btn-primary']) }}
        <hr>

        @include('app.includes.errors')

        {!! Form::open(['route'=>'attendance.store']) !!}

        @include('app.attendance.form')
        <button type="submit" name="office_time" id="arrival_time" class="btn btn-info btn-lg" value="arrival_time"><i class="fa fa-calendar-check-o" aria-hidden="true"> Arrival Time</i>
        </button>

        <button type="submit" name="office_time" id="departure_time" class="btn btn-success btn-lg" value="departure_time"><i class="fa fa-calendar-check-o" aria-hidden="true"> Departure Time</i>
        </button>


        {!! Form::close() !!}


    </div>


@stop

resources/views/app/attendance/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 form-padding">
        <label class="col-xs-12 col-sm-12 col-md-8" >Name</label>
        <div class="col-xs-12 col-sm-12 col-md-6 form-padding">
            <select id="staff_id" name="staff_id" class="form-control">
                  @foreach($staff as $s)
                    <option value="{{ $s->id }}">{{ $s->first_name." ".$s->last_name }}</option>

                @endforeach
            </select>
        </div>
    </div>
</div>

resources/views/app/includes/errors.blade.php
	{{--@if($errors->any())--}}
	    {{--<div class="alert alert-danger">--}}
	        {{--@foreach($errors->all() as $error)--}}
	            {{--<p>{{ $error }}</p>--}}
	        {{--@endforeach--}}
	    {{--</div>--}}
	{{--@endif--}}

	@if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
    @endif

    @if(Session::has('delete_message'))
        <div class="alert alert-danger">
            {{ Session::get('delete_message') }}
        </div>
    @endif

resources/views/app/includes/head.blade.php
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Staff Management System</title>

    <!-- Bootstrap Core CSS -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="public/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="public/css/style.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="public/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.5.4/bootstrap-select.min.css">
    <link rel="stylesheet" href="public/css/bootstrap-timepicker.min.css">

    <script src="public/js/bootstrap-timepicker.min.js"></script>

resources/views/app/includes/nav.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Staff Management System</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <!-- Massege -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                </li>                
                <!-- End-Massege -->

                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                        </li>
                        
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

resources/views/app/includes/script.blade.php
    <script src="public/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="bootstrap/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="public/js/sb-admin-2.min.js"></script>

resources/views/app/includes/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{{ url('/home') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ url('/staff') }}"><i class="fa fa-users fa-fw"></i> Staff</a>
                        </li>
                        <li>
                            <a href="{{ url('/attendance') }}"><i class="fa fa-sticky-note-o fa-fw"></i> Attendance</a>
                        </li>
                        <li>
                            <a href="{{ url('/salary') }}"><i class="fa fa-money"></i> Salary</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

resources/views/app/layouts/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Staff Management System</title>

    <!-- Bootstrap Core CSS -->
    <link href="../bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../public/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="../public/css/style.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="../public/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">


    <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.5.4/bootstrap-select.min.css">

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
            @include('app.includes.nav')

        <!-- End Navigation -->

        <!-- Sidebar -->
            @include('app.includes.sidebar')

        <!-- End Sidebar -->
            
        @yield('content')
            

        
    </div>
    <!-- /#wrapper -->

    

</body>

    <script src="../public/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../bootstrap/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../public/js/sb-admin-2.min.js"></script>



</html>

resources/views/app/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
     @include('app.includes.head')
    
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
            @include('app.includes.nav')

        <!-- End Navigation -->

        <!-- Sidebar -->
            @include('app.includes.sidebar')

        <!-- End Sidebar -->
            
        @yield('content')
            

        
    </div>
    <!-- /#wrapper -->

    

</body>

    @include('app.includes.script')


</html>

resources/views/app/layouts/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Staff Management System</title>

    <!-- Bootstrap Core CSS -->
    <link href="../../bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="../../public/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="../../public/css/style.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="../../public/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.5.4/bootstrap-select.min.css">    
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
            @include('app.includes.nav')

        <!-- End Navigation -->

        <!-- Sidebar -->
            @include('app.includes.sidebar')

        <!-- End Sidebar -->
            
        @yield('content')
            

        
    </div>
    <!-- /#wrapper -->

    

</body>

    <script src="../../public/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../../bootstrap/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../../public/js/sb-admin-2.min.js"></script>



</html>

resources/views/app/pages/home.blade.php
@extends('app.layouts.default')
@section('content')

@stop

resources/views/app/salary/index.blade.php
@extends('app.layouts.default')
@section('content')

<div class="container">
	<h1>Salary</h1>
	<hr>

   <div class="row">
       <div class="col-md-9">
           

       </div>
       <div class="col-md-3">
        <h3>Staff list</h3>
           <table class="table">
        <thead>
           <tr>
                <th>Card No.</th>
                <th>Name</th>
                <th>Post</th>
            </tr> 
        </thead>
        <tbody>
        @foreach($staff as $s)
                    <tr>
                        <td>{{ $s->first_name }}</td>
                        <td><a href="{{ route('salary.show', [$s->id]) }}">{{ $s->first_name." ".$s->last_name }}</a></td>
                        <td>{{ $s->position }}</td>
                    </tr>
        @endforeach
        </tbody>
    </table>

       </div>
    </div>

</div>











   
</div>

@stop

resources/views/app/staff/create.blade.php
@extends('app.layouts.create')
@section('content')

<div class="container">
    <h1>Register staff</h1>
    {{ link_to_route('staff.index', 'View All Staff', null,['class'=>'btn btn-primary']) }}
    <hr>

    @include('app.includes.errors')

    {!! Form::open(['route'=>'staff.store', 'files'=>true]) !!}

    @include('app.staff.form')

    {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}

    @include('app.staff.upload')

     

</div>

@stop

resources/views/app/staff/edit.blade.php
@extends('app.layouts.edit')
@section('content')

<div class="container">
<h1>Edit</h1>
{{ link_to_route('staff.index', 'View All Staff', null,['class'=>'btn btn-primary']) }}
<hr>

	@include('app.includes.errors')

{!! Form::model($staff, [
    'method' => 'PATCH',
    'route' => ['staff.update', $staff->id]
]) !!}	
	<div align="right">
	    {{ Form::reset('Reset All', ['class' =>'btn btn-warning']) }}
	</div>
    @include('app.staff.form')

    {!! Form::submit('Update', ['class' => 'btn btn-success']) !!}



{!! Form::close() !!}
</div>
@stop

resources/views/app/staff/index.blade.php
@extends('app.layouts.default')
@section('content')

<div class="container">
	<h1>Staff Information<!--  <small><a href="{{ url('/staff/create') }}">Register Staff</a></small> --></h1>
  {{ link_to_route('staff.create', 'Register Staff', null,['class'=>'btn btn-primary']) }}

	<hr>
           <div class="panel panel-default panel-table">
           
            <div class="panel-heading">
              <div class="row">
                	
                  <div class="col col-xs-12 text-right">
                    <!--Search -->
                    {!! Form::open(['url' => '/staff', 'method' => 'GET', 'class' => 'navbar-form navbar-right', 'role' => 'search']) !!}
                        {!! Form::text('search', Request::get('search'), ['class' => 'form-control', 'placeholder'   => Lang::get('Search...')]) !!}
                    {!! Form::close() !!}
                    <!--End search-->
                  </div>
              </div>
            </div>
            <div class="panel-body">
                @include('app.includes.errors')
                <table class="table table-striped table-bordered table-list">
                <thead>
                  <tr>
                    <th class="text-center">Name</th>
                    <th class="text-center">Position</th>
                    <th class="text-center">Mobile</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Action</th>
                    <th class="text-center">Delete</th>
                  </tr> 
                </thead>
                <tbody>
                @foreach($staff as $s)
                    <tr>
                      <td>{{ $s->first_name." ".$s->last_name }}</td>
                      <td>{{ $s->position }}</td>
                      <td>{{ $s->mobile }}</td>
                      <td>{{ $s->email }}</td>
                      <td align="center">
                        <a class="btn btn-info" href="{{ url('/staff/show', $s->id) }}">View</a>
                        <b>|</b>
                        {{ link_to_route('staff.edit', 'Edit', [$s->id], ['class'=>'btn btn-info']) }}
                      </td>
                      <td align="center">
                          {!! Form::open(array(
                                        'route'=>[
                                                    'staff.destroy', $s->id],
                                        'method' => 'DELETE')) !!}
                          {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                          {!! Form::close() !!}
                      </td>
                    </tr>
                  @endforeach
                </tbody>

              </table>
                <div class="col col-xs-12 text-right">
                    <?= $staff->render() ?>
                </div>
             </div>
          </div>
</div>
@stop

resources/views/app/staff/show.blade.php
@extends('app.layouts.edit')
@section('content')

<div class="container">

<h1>Staff Information</h1>
    {{ link_to_route('staff.index', 'View All Staff', null,['class'=>'btn btn-primary']) }}
    <hr>

	<div class="table-responsive">

		<table class="table table-bordered">
			<tr>
				<th width="25%">Name</th>
				<td>{{ $staff->first_name." ".$staff->last_name }}</td>
			</tr>

			<tr>
				<th width="25%">Email</th>	
				<td>{{ $staff->email }}</td>
			</tr>

			<tr>
				<th width="25%">Mobile</th>	
				<td>{{ $staff->mobile }}</td>
			</tr>

			<tr>
				<th width="25%">CV</th>	
				<td>{{ $staff->cv }}</td>
			</tr>

			<tr>
				<th width="25%">Photo</th>	
				<td>{{ $staff->photo }}</td>
			</tr>

			<tr>
				<th width="25%">Address</th>	
				<td>{{ $staff->address }}</td>
			</tr>
		</table>
		
	</div>

	<div>

		{{ link_to_route('staff.edit', 'Edit', [$staff->id], ['class'=>'btn btn-info']) }}

		<div class="pull-right">
		{!! Form::open(array(
                              'route'=>[
                              'staff.destroy', $staff->id],
                              'method' => 'DELETE')) !!}
         	  

        {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

     
	    {!! Form::close() !!}
		
		</div>
	</div>
	
</div>


@stop

resources/views/app/staff/upload.blade.php
	{!! Form::open(array('url' => '/staff/file/handleUpload', 'files' => true)) !!}

        <!-- Upload Image -->
    	<div class="col-xs-12 col-sm-12 col-md-6 form-padding">
            {!! Form::label('photo', ' Photo', ['class' => 'control-label']) !!}
            {{ Form::file('file', ['class' => 'field']) }}
            {!! Form::token() !!}
            {!! Form::submit('Upload') !!}
        </div>
        
    {!! Form::close() !!}

    {!! Form::open(array('url' => '/staff/file/handleUpload', 'files' => true)) !!}

        <!-- Upload CV -->
        <div class="col-xs-12 col-sm-12 col-md-6 form-padding">
            {!! Form::label('cv', ' CV', ['class' => 'control-label']) !!}
            {{ Form::file('file', ['class' => 'field']) }}
            {!! Form::token() !!}
            {!! Form::submit('Upload') !!}
        </div>

    {!! Form::close() !!}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Laravel</title>

    <!-- Styles -->
    <link href="public/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/home') }}">
                    Human Resource Information System
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/') }}">Login</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Scripts -->
    <script src="public/js/app.js"></script>
</body>
</html>